### ISSUE TITLE
Have png's in same directory?

### ISSUE THREAD

**Issue by mrmartineau** [gavro/gulp-iconify#11]
Is there any reason why I cannot have source pngs in the same directory as the svgs? I am moving from Grunt/grunticon where this was possible...

Cheers

**Comment by gavro** [comment]
Hmm, I don't see why that's not possible? If you use the same folder setting for _pngOutput_ as for _src_ the generated PNGs (there are no source PNGs) will be placed alongside the source SVGs.

E.g.

```
gulp.task('default', function() {
    iconify({
        src: './img/icons/*.svg',
        pngOutput: './img/icons'
    });
});
```

will get you want you want (not tested).

Could you confirm that? Thnx!

**Comment by mrmartineau** [comment]
I will try it when I get to work tomorrow. Thanks

**Comment by gavro** [comment]
Closing this, works as posted when testing here.
