### ISSUE TITLE
File name of scss output

### ISSUE THREAD

**Issue by Matthieusch** [gavro/gulp-iconify#16]
Hi,

File name of scss output should starting by '_' like: _icon.svg.scss.
Because when lib-sass compile these files, it'll create : icon.svg.css, icon.png.css and icon.fallback.css in dist folder.
I think users can import these files as a dependencies in there main.scss like so: 
`@import "icon.svg";`

What do you think?

**Comment by gavro** [comment]
Hm, sounds like a plan. Will push this to a future 0.4.\* version so that it doesn't break any setups using 0.3.*. Thanks for spotting this!

**Comment by SeeWatson** [comment]
This would be incredibly helpful to me. Has there been any progress on it?

**Comment by CHEWX** [comment]
Agreed. 

Needs a '_', it does compile correctly by using @import but duplicates output.

**Comment by ttomdewit** [comment]
Any news on this? Issue seems to be closed, but unfortunately 0.4.0 does not prepend filenames with `_` (`_icons.svg.scss`).

**Comment by ttomdewit** [comment]
Any news on this?

**Comment by SeeWatson** [comment]
I'd like to see some movement as well. At least give the option to prepend with an _ even if it's not the default.

**Comment by gavro** [comment]
Fixed/added to v0.6.0. Scss is written to "underscore files" and css to regular icons.css files. Needed to replace the gulp-sass plugin with a customised one, as "underscore files" are treated as partial files and are not processed by gulp-sass.
