### ISSUE TITLE
Disable scssOutput?

### ISSUE THREAD

**Issue by thisisjamessmith** [gavro/gulp-iconify#2]
Hiya, thanks for making this it's really great...

But I'm not understanding the point of rendering the .scss files, since they are compiled to css anyway, and need to be forked for delivery to different browers, so there's no point in integrating them into the core CSS. Is it possible to disable the scssOutput altogether?

**Comment by gavro** [comment]
Hmm, you've got a valid point. Internally (on 1 project) we use the outputted SCSS rather than the CSS code because we needed some post-processing outside of this gulp-task. But yea, this should be an option.

Option (a compatible option) will be added soon. Thanks!

**Comment by thisisjamessmith** [comment]
great thanks :-)
