### ISSUE TITLE
npm install failing to download node-sass

### ISSUE THREAD

**Issue by sethcwhiting** [gavro/gulp-iconify#24]
When running "npm install gulp-iconify --save-dev," it seems to run smoothly until I get to the node-sass module. Then it gives me this warning:

" npm WARN deprecated pangyp@2.3.3: use node-gyp@3+ instead "

And this error:

" Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-4.1/binding.node "

I'm not sure how related the two are, but I did install the latest version of node-gyp (3.1.0) before I ran the command, and when I visit the raw.githubusercontent url, it just says "Not Found."

Any help I can get on this would be very appreciated. I'm looking forward to iconifying my svgs!

**Comment by ghost** [comment]
There are no bindings for the most recent node versions in old node-sass, only after node-sass v3.4
I'm dealing with the same thing upgrading my projects dependencies. This is the last package that I need to deal with.

There are 2 PR on the queue here to fix this.

**Comment by gavro** [comment]
Version 0.4.0 incorporates pull request #23. So the install should work fine finally :)
