### ISSUE TITLE
Concurrency limit for gulp-svg2png

### ISSUE THREAD

**Issue by sillero** [gavro/gulp-iconify#28]
`gulp-svg2png` reached version `1.0.0` and now accepts a concurrency limit option to improve performance. This concurrency limitation greatly improved the build time on the project I'm working on.

I'll be submitting a PR for this.

**Comment by gavro** [comment]
Thank you for the pull request. I've finally merged it, sorry for the huge delay. Will try to give this lib some more attention :)
