### ISSUE TITLE
Don't use base64 embed

### ISSUE THREAD

**Issue by bkastl** [gavro/gulp-iconify#3]
You don't have to encode SVGs as base64 when they are embedded, they just add data overhead (usually 33%).

They can be embedded just like this:
`background: url('data:image/svg+xml;utf8,<svg ...> ... </svg>');`

Reference:
http://css-tricks.com/probably-dont-base64-svg/

**Comment by gavro** [comment]
Thanks, already had this on my todo list and you're absolutely right! Will bump it on my prio list to get this fixed a.s.a.p!
