### ISSUE TITLE
svg2png error on macOS Sierra 

### ISSUE THREAD

**Issue by Rychetsky** [gavro/gulp-iconify#32]
Since the update to macOS Sierra I get this error message:
/node_modules/gulp-iconify/node_modules/gulp-svg2png/index.js:49
        throw new gutil.PluginError(PLUGIN_NAME, message);
              ^
Error: Error while converting image.Error: Command failed: 

Not sure how to remove this error. Has somebody else this problem?

**Comment by matthewmcclatchie** [comment]
Exactly the same issue. It's been discussed over in the gulp-svg2png repo: https://github.com/akoenig/gulp-svg2png/issues/28
I've tried a few of the solutions posted there but have had no luck yet.

**Comment by matthewmcclatchie** [comment]
@Rychetsky So after re-reading aaronbushnell's comment in here: akoenig/gulp-svg2png#28
I uninstalled gulp-iconify, upgrade Node to v6.7.0 and then installed gulp-svg2png v2.0.2 (both latest versions at time of writing) and things seem to be working. 

I'm at least getting a successful conversion of a single SVG to a PNG, I haven't messed around with any configuration yet but it's a step in the right direction!

**Comment by gavro** [comment]
@matthewmcclatchie thanks for that, latest commit updates the dep to 2.\* (+some other things). I'll try to add/change some more stuff before I bump a new version.
