### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by JamesNock** [gavro/gulp-iconify#33]
Hi, when I run npm install with '"gulp-iconify": "^0.5.0"' in my dependencies I get the following error:

Error extracting /Users/jamesnock/.npm/fs/0.0.0/package.tgz archive: ENOENT: no such file or directory, open '/Users/jamesnock/.npm/fs/0.0.0/package.tgz'

When I inspect the contents of '/Users/jamesnock/.npm/fs/' I have a folder named '0.0.2' rather than '0.0.0' which is causing the issue. Any ideas on how to fix?

**Comment by gavro** [comment]
@JamesNock could you check whether v0.6.0 solves this for you (it should)? Thnx!

**Comment by JamesNock** [comment]
Fixed it! Nice one @gavro
