### ISSUE TITLE
SVGO is breaking images

### ISSUE THREAD

**Issue by brudil** [gavro/gulp-iconify#6]
SVGO is breaking lots of our images. We actually use svgo but had to disable some of the optimizations. ('removeUnknownsAndDefaults' and 'mergePaths')

Could svgo be outright skipped with an option?

**Comment by gavro** [comment]
Could you send me some example-SVGs where this is happening?

If I remember correctly, SVGO is also used to get a correct image: The original image is already piped through imacss (purify/slugify/urify), so we only have an (uri)encoded image at this point.

Will have a look if that's correct...

**Comment by brudil** [comment]
- [source](https://s3.amazonaws.com/brudil-share/files/Z1GDqjYu2/base) | [broken](https://s3.amazonaws.com/brudil-share/files/bkMgFotd3/base)
- [source](https://s3.amazonaws.com/brudil-share/files/bJcOG2t_3/base) | [broken](https://s3.amazonaws.com/brudil-share/files/-JWNEhY_2/base)

Commenting out L34 `lib/iconify.js` doesn't seem to cause any errors and stops SVGO from mangling the images.

**Comment by gavro** [comment]
Okay, so line 37 needs to remain where it is, otherwise you'll get the base64 encoded image. Line 28-35 should be executed as an option. I think I'll make the option an opt-out one (optimize by default, production-ready files)... on the other hand, if SVGO is still not as 'stable' as I'd thought perhaps it really should be an opt-in... I could introduce an extra SVGO param-option (pass params to SVGO call).

FYI: https://github.com/svg/svgo/issues/217

**Comment by brudil** [comment]
Our workflow does the image optimization before iconify is started, so skipping SVGO entirely as an option would be great. For those that don't have the slightly more convoluted pipeline we do, being able to passin a custom SVGO options object would be useful.

Perhaps by default svgo is run with defaults, then an svgo option can either be set to false where it doesn't run, or an object that's passed directly to the svgo instance?

Once that svgo change lands it seems like most images will work without issue.

**Comment by gavro** [comment]
Fixed with: https://github.com/gavro/gulp-iconify/commit/c3bd2246050ca51d5394ae577504db8e84de86c5

See readme:

###Customized example

``` javascript
gulp.task('default', function() {
    iconify({
        src: './img/icons/*.svg',
        pngOutput: './img/icons/png',
        scssOutput: './scss',
        cssOutput:  './css',
        styleTemplate: '_icon_gen.scss.mustache'
        svgoOptions: {
            enabled: true,
            options: {
                plugins: [
                    { removeUnknownsAndDefaults: false },
                    { mergePaths: false }
                ]
            }
        }
    });
});
```

Note: To disable SVGO, just set `svgoOptions: { enabled: ___ }` to anything but `true` .

**Comment by brudil** [comment]
Brilliant. Cheers.
