### ISSUE TITLE
No CSS output needed

### ISSUE THREAD

**Issue by Rychetsky** [gavro/gulp-iconify#7]
Is it possible to disable the css output? In my project I only the SCSS files.

**Comment by gavro** [comment]
Sounds like an edge case, but I'll see if I can get this in as well (it might clash with fallbacks and the optional SCSS output).

**Comment by DonGissel** [comment]
I wouldn't call it an edge case. Most large web projects use some form of preprocessor as opposed to pure CSS, so being able to disable the final CSS-render would greatly benefit those of us depending on LESS or SASS.

**Comment by gavro** [comment]
Fixed by PR https://github.com/gavro/gulp-iconify/pull/14
